### ISSUE TITLE
Does close Unity view destroys the session of Unity or does it run in the bacground.

### ISSUE THREAD

**Issue by suman2085** [s1mar/UniyAndroidMashup#1]
Hello there,
                   This repo is very informative and thanks for taking intiative to do something for andorid. I have a doubt. When you are in Unity view and when you press back button what happens to the Unity view..Is it paused or runs in the background or is it destroyed..Please reply here so that it can help me a lot..Thank you in advance.

**Comment by s1mar** [comment]
Sorry for the late response, I was suffering from dengue. The View goes into the background, it isn't destroyed.
